language: node_js
jobs:
  include:
    - stage: linux
      os: linux
      dist:
      - precise
      - trusty
      - xenial
      script:
      - tsc
      - node travis_test
    - stage: osx
      os: osx
      script:
      - tsc
      - node travis_test
    